[project]
name = 'deno-clarigen'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.ft-trait'

[[project.requirements]]
contract_id = 'SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin'
[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 2
epoch = 2.1

[contracts.pox2]
path = 'contracts/pox-2-boot.clar'
clarity_version = 2
epoch = 2.1

[contracts.tester]
path = 'contracts/tester.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
