[project]
name = "deno-clarigen"
authors = []
description = ""
telemetry = false
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.ft-trait"

[project.cache_location]
path = ".requirements"

[contracts.counter]
path = "contracts/counter.clar"
clarity_version = 2

[contracts.tester]
path = "contracts/tester.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
