# Set to your project's Clarinet config file
clarinet = "./Clarinet.toml"

# Set where you'd like Deno types output.
# Comment or remove section to skip Deno types
[deno]
# `output` can be a directory or a folder.
output = "artifacts/clarigen/index.ts"
helper = "tests/helper.ts"

# Set where you'd like ESM types output.
# Comment or remove section to skip ESM types
[esm]
# `output` can be a directory or a folder.
outputs = ["esm/index.ts", "esm/2.ts"]
include_accounts = true

# `esm.after` - script to run after ESM types are generated.
# examples:
# after = "yarn prettier ./esm/index.ts"
# after = "echo 'yay'"
after = "deno fmt ./esm/index.ts"

# Set where you'd like generated contract docs
# Generate docs by running `clarigen docs`
[docs]
# `output` should be a folder
output = "docs"
exclude = ["ft-trait"]